<?php

namespace App\DataFixtures;

use App\Entity\Country;
use Doctrine\Persistence\ObjectManager;

class CountryFixture extends AbstractBaseFixtures
{
    private array $countries = [
        ['id' => 1, 'name' => 'Afghanistan', 'iso' => 'AF'],
        ['id' => 2, 'name' => 'Albania', 'iso' => 'AL'],
        ['id' => 3, 'name' => 'Algeria', 'iso' => 'DZ'],
        ['id' => 4, 'name' => 'American Samoa', 'iso' => 'AS'],
        ['id' => 5, 'name' => 'Andorra', 'iso' => 'AD'],
        ['id' => 6, 'name' => 'Angola', 'iso' => 'AO'],
        ['id' => 7, 'name' => 'Anguilla', 'iso' => 'AI'],
        ['id' => 8, 'name' => 'Antarctica', 'iso' => 'AQ'],
        ['id' => 9, 'name' => 'Antigua and Barbuda', 'iso' => 'AG'],
        ['id' => 10, 'name' => 'Argentina', 'iso' => 'AR'],
        ['id' => 11, 'name' => 'Armenia', 'iso' => 'AM'],
        ['id' => 12, 'name' => 'Aruba', 'iso' => 'AW'],
        ['id' => 13, 'name' => 'Australia', 'iso' => 'AU'],
        ['id' => 14, 'name' => 'Austria', 'iso' => 'AT'],
        ['id' => 15, 'name' => 'Azerbaijan', 'iso' => 'AZ'],
        ['id' => 16, 'name' => 'Bahamas', 'iso' => 'BS'],
        ['id' => 17, 'name' => 'Bahrain', 'iso' => 'BH'],
        ['id' => 18, 'name' => 'Bangladesh', 'iso' => 'BD'],
        ['id' => 19, 'name' => 'Barbados', 'iso' => 'BB'],
        ['id' => 20, 'name' => 'Belarus', 'iso' => 'BY'],
        ['id' => 21, 'name' => 'Belgium', 'iso' => 'BE'],
        ['id' => 22, 'name' => 'Belize', 'iso' => 'BZ'],
        ['id' => 23, 'name' => 'Benin', 'iso' => 'BJ'],
        ['id' => 24, 'name' => 'Bermuda', 'iso' => 'BM'],
        ['id' => 25, 'name' => 'Bhutan', 'iso' => 'BT'],
        ['id' => 26, 'name' => 'Bolivia', 'iso' => 'BO'],
        ['id' => 27, 'name' => 'Bosnia and Herzegovina', 'iso' => 'BA'],
        ['id' => 28, 'name' => 'Botswana', 'iso' => 'BW'],
        ['id' => 29, 'name' => 'Bouvet Island', 'iso' => 'BV'],
        ['id' => 30, 'name' => 'Brazil', 'iso' => 'BR'],
        ['id' => 31, 'name' => 'British Indian Ocean Territory', 'iso' => 'IO'],
        ['id' => 32, 'name' => 'Brunei Darussalam', 'iso' => 'BN'],
        ['id' => 33, 'name' => 'Bulgaria', 'iso' => 'BG'],
        ['id' => 34, 'name' => 'Burkina Faso', 'iso' => 'BF'],
        ['id' => 35, 'name' => 'Burundi', 'iso' => 'BI'],
        ['id' => 36, 'name' => 'Cambodia', 'iso' => 'KH'],
        ['id' => 37, 'name' => 'Cameroon', 'iso' => 'CM'],
        ['id' => 38, 'name' => 'Canada', 'iso' => 'CA'],
        ['id' => 39, 'name' => 'Cape Verde', 'iso' => 'CV'],
        ['id' => 40, 'name' => 'Cayman Islands', 'iso' => 'KY'],
        ['id' => 41, 'name' => 'Central African Republic', 'iso' => 'CF'],
        ['id' => 42, 'name' => 'Chad', 'iso' => 'TD'],
        ['id' => 43, 'name' => 'Chile', 'iso' => 'CL'],
        ['id' => 44, 'name' => 'China', 'iso' => 'CN'],
        ['id' => 45, 'name' => 'Christmas Island', 'iso' => 'CX'],
        ['id' => 46, 'name' => 'Cocos (Keeling) Islands', 'iso' => 'CC'],
        ['id' => 47, 'name' => 'Colombia', 'iso' => 'CO'],
        ['id' => 48, 'name' => 'Comoros', 'iso' => 'KM'],
        ['id' => 49, 'name' => 'Congo', 'iso' => 'CG'],
        ['id' => 50, 'name' => 'Congo, the Democratic Republic of the', 'iso' => 'CD'],
        ['id' => 51, 'name' => 'Cook Islands', 'iso' => 'CK'],
        ['id' => 52, 'name' => 'Costa Rica', 'iso' => 'CR'],
        ['id' => 53, 'name' => 'Cote D\'Ivoire', 'iso' => 'CI'],
        ['id' => 54, 'name' => 'Croatia', 'iso' => 'HR'],
        ['id' => 55, 'name' => 'Cuba', 'iso' => 'CU'],
        ['id' => 56, 'name' => 'Cyprus', 'iso' => 'CY'],
        ['id' => 57, 'name' => 'Czech Republic', 'iso' => 'CZ'],
        ['id' => 58, 'name' => 'Denmark', 'iso' => 'DK'],
        ['id' => 59, 'name' => 'Djibouti', 'iso' => 'DJ'],
        ['id' => 60, 'name' => 'Dominica', 'iso' => 'DM'],
        ['id' => 61, 'name' => 'Dominican Republic', 'iso' => 'DO'],
        ['id' => 62, 'name' => 'Ecuador', 'iso' => 'EC'],
        ['id' => 63, 'name' => 'Egypt', 'iso' => 'EG'],
        ['id' => 64, 'name' => 'El Salvador', 'iso' => 'SV'],
        ['id' => 65, 'name' => 'Equatorial Guinea', 'iso' => 'GQ'],
        ['id' => 66, 'name' => 'Eritrea', 'iso' => 'ER'],
        ['id' => 67, 'name' => 'Estonia', 'iso' => 'EE'],
        ['id' => 68, 'name' => 'Ethiopia', 'iso' => 'ET'],
        ['id' => 69, 'name' => 'Falkland Islands (Malvinas)', 'iso' => 'FK'],
        ['id' => 70, 'name' => 'Faroe Islands', 'iso' => 'FO'],
        ['id' => 71, 'name' => 'Fiji', 'iso' => 'FJ'],
        ['id' => 72, 'name' => 'Finland', 'iso' => 'FI'],
        ['id' => 73, 'name' => 'France', 'iso' => 'FR'],
        ['id' => 74, 'name' => 'French Guiana', 'iso' => 'GF'],
        ['id' => 75, 'name' => 'French Polynesia', 'iso' => 'PF'],
        ['id' => 76, 'name' => 'French Southern Territories', 'iso' => 'TF'],
        ['id' => 77, 'name' => 'Gabon', 'iso' => 'GA'],
        ['id' => 78, 'name' => 'Gambia', 'iso' => 'GM'],
        ['id' => 79, 'name' => 'Georgia', 'iso' => 'GE'],
        ['id' => 80, 'name' => 'Germany', 'iso' => 'DE'],
        ['id' => 81, 'name' => 'Ghana', 'iso' => 'GH'],
        ['id' => 82, 'name' => 'Gibraltar', 'iso' => 'GI'],
        ['id' => 83, 'name' => 'Greece', 'iso' => 'GR'],
        ['id' => 84, 'name' => 'Greenland', 'iso' => 'GL'],
        ['id' => 85, 'name' => 'Grenada', 'iso' => 'GD'],
        ['id' => 86, 'name' => 'Guadeloupe', 'iso' => 'GP'],
        ['id' => 87, 'name' => 'Guam', 'iso' => 'GU'],
        ['id' => 88, 'name' => 'Guatemala', 'iso' => 'GT'],
        ['id' => 89, 'name' => 'Guinea', 'iso' => 'GN'],
        ['id' => 90, 'name' => 'Guinea-Bissau', 'iso' => 'GW'],
        ['id' => 91, 'name' => 'Guyana', 'iso' => 'GY'],
        ['id' => 92, 'name' => 'Haiti', 'iso' => 'HT'],
        ['id' => 93, 'name' => 'Heard Island and Mcdonald Islands', 'iso' => 'HM'],
        ['id' => 94, 'name' => 'Holy See (Vatican City State)', 'iso' => 'VA'],
        ['id' => 95, 'name' => 'Honduras', 'iso' => 'HN'],
        ['id' => 96, 'name' => 'Hong Kong', 'iso' => 'HK'],
        ['id' => 97, 'name' => 'Hungary', 'iso' => 'HU'],
        ['id' => 98, 'name' => 'Iceland', 'iso' => 'IS'],
        ['id' => 99, 'name' => 'India', 'iso' => 'IN'],
        ['id' => 100, 'name' => 'Indonesia', 'iso' => 'ID'],
        ['id' => 101, 'name' => 'Iran, Islamic Republic of', 'iso' => 'IR'],
        ['id' => 102, 'name' => 'Iraq', 'iso' => 'IQ'],
        ['id' => 103, 'name' => 'Ireland', 'iso' => 'IE'],
        ['id' => 104, 'name' => 'Israel', 'iso' => 'IL'],
        ['id' => 105, 'name' => 'Italy', 'iso' => 'IT'],
        ['id' => 106, 'name' => 'Jamaica', 'iso' => 'JM'],
        ['id' => 107, 'name' => 'Japan', 'iso' => 'JP'],
        ['id' => 108, 'name' => 'Jordan', 'iso' => 'JO'],
        ['id' => 109, 'name' => 'Kazakhstan', 'iso' => 'KZ'],
        ['id' => 110, 'name' => 'Kenya', 'iso' => 'KE'],
        ['id' => 111, 'name' => 'Kiribati', 'iso' => 'KI'],
        ['id' => 112, 'name' => 'Korea, Democratic People\'s Republic of', 'iso' => 'KP'],
        ['id' => 113, 'name' => 'Korea, Republic of', 'iso' => 'KR'],
        ['id' => 114, 'name' => 'Kuwait', 'iso' => 'KW'],
        ['id' => 115, 'name' => 'Kyrgyzstan', 'iso' => 'KG'],
        ['id' => 116, 'name' => 'Lao People\'s Democratic Republic', 'iso' => 'LA'],
        ['id' => 117, 'name' => 'Latvia', 'iso' => 'LV'],
        ['id' => 118, 'name' => 'Lebanon', 'iso' => 'LB'],
        ['id' => 119, 'name' => 'Lesotho', 'iso' => 'LS'],
        ['id' => 120, 'name' => 'Liberia', 'iso' => 'LR'],
        ['id' => 121, 'name' => 'Libyan Arab Jamahiriya', 'iso' => 'LY'],
        ['id' => 122, 'name' => 'Liechtenstein', 'iso' => 'LI'],
        ['id' => 123, 'name' => 'Lithuania', 'iso' => 'LT'],
        ['id' => 124, 'name' => 'Luxembourg', 'iso' => 'LU'],
        ['id' => 125, 'name' => 'Macao', 'iso' => 'MO'],
        ['id' => 126, 'name' => 'Macedonia, the Former Yugoslav Republic of', 'iso' => 'MK'],
        ['id' => 127, 'name' => 'Madagascar', 'iso' => 'MG'],
        ['id' => 128, 'name' => 'Malawi', 'iso' => 'MW'],
        ['id' => 129, 'name' => 'Malaysia', 'iso' => 'MY'],
        ['id' => 130, 'name' => 'Maldives', 'iso' => 'MV'],
        ['id' => 131, 'name' => 'Mali', 'iso' => 'ML'],
        ['id' => 132, 'name' => 'Malta', 'iso' => 'MT'],
        ['id' => 133, 'name' => 'Marshall Islands', 'iso' => 'MH'],
        ['id' => 134, 'name' => 'Martinique', 'iso' => 'MQ'],
        ['id' => 135, 'name' => 'Mauritania', 'iso' => 'MR'],
        ['id' => 136, 'name' => 'Mauritius', 'iso' => 'MU'],
        ['id' => 137, 'name' => 'Mayotte', 'iso' => 'YT'],
        ['id' => 138, 'name' => 'Mexico', 'iso' => 'MX'],
        ['id' => 139, 'name' => 'Micronesia, Federated States of', 'iso' => 'FM'],
        ['id' => 140, 'name' => 'Moldova, Republic of', 'iso' => 'MD'],
        ['id' => 141, 'name' => 'Monaco', 'iso' => 'MC'],
        ['id' => 142, 'name' => 'Mongolia', 'iso' => 'MN'],
        ['id' => 143, 'name' => 'Montserrat', 'iso' => 'MS'],
        ['id' => 144, 'name' => 'Morocco', 'iso' => 'MA'],
        ['id' => 145, 'name' => 'Mozambique', 'iso' => 'MZ'],
        ['id' => 146, 'name' => 'Myanmar', 'iso' => 'MM'],
        ['id' => 147, 'name' => 'Namibia', 'iso' => 'NA'],
        ['id' => 148, 'name' => 'Nauru', 'iso' => 'NR'],
        ['id' => 149, 'name' => 'Nepal', 'iso' => 'NP'],
        ['id' => 150, 'name' => 'Netherlands', 'iso' => 'NL'],
        ['id' => 151, 'name' => 'Netherlands Antilles', 'iso' => 'AN'],
        ['id' => 152, 'name' => 'New Caledonia', 'iso' => 'NC'],
        ['id' => 153, 'name' => 'New Zealand', 'iso' => 'NZ'],
        ['id' => 154, 'name' => 'Nicaragua', 'iso' => 'NI'],
        ['id' => 155, 'name' => 'Niger', 'iso' => 'NE'],
        ['id' => 156, 'name' => 'Nigeria', 'iso' => 'NG'],
        ['id' => 157, 'name' => 'Niue', 'iso' => 'NU'],
        ['id' => 158, 'name' => 'Norfolk Island', 'iso' => 'NF'],
        ['id' => 159, 'name' => 'Northern Mariana Islands', 'iso' => 'MP'],
        ['id' => 160, 'name' => 'Norway', 'iso' => 'NO'],
        ['id' => 161, 'name' => 'Oman', 'iso' => 'OM'],
        ['id' => 162, 'name' => 'Pakistan', 'iso' => 'PK'],
        ['id' => 163, 'name' => 'Palau', 'iso' => 'PW'],
        ['id' => 164, 'name' => 'Palestinian Territory, Occupied', 'iso' => 'PS'],
        ['id' => 165, 'name' => 'Panama', 'iso' => 'PA'],
        ['id' => 166, 'name' => 'Papua New Guinea', 'iso' => 'PG'],
        ['id' => 167, 'name' => 'Paraguay', 'iso' => 'PY'],
        ['id' => 168, 'name' => 'Peru', 'iso' => 'PE'],
        ['id' => 169, 'name' => 'Philippines', 'iso' => 'PH'],
        ['id' => 170, 'name' => 'Pitcairn', 'iso' => 'PN'],
        ['id' => 171, 'name' => 'Poland', 'iso' => 'PL'],
        ['id' => 172, 'name' => 'Portugal', 'iso' => 'PT'],
        ['id' => 173, 'name' => 'Puerto Rico', 'iso' => 'PR'],
        ['id' => 174, 'name' => 'Qatar', 'iso' => 'QA'],
        ['id' => 175, 'name' => 'Reunion', 'iso' => 'RE'],
        ['id' => 176, 'name' => 'Romania', 'iso' => 'RO'],
        ['id' => 177, 'name' => 'Russian Federation', 'iso' => 'RU'],
        ['id' => 178, 'name' => 'Rwanda', 'iso' => 'RW'],
        ['id' => 179, 'name' => 'Saint Helena', 'iso' => 'SH'],
        ['id' => 180, 'name' => 'Saint Kitts and Nevis', 'iso' => 'KN'],
        ['id' => 181, 'name' => 'Saint Lucia', 'iso' => 'LC'],
        ['id' => 182, 'name' => 'Saint Pierre and Miquelon', 'iso' => 'PM'],
        ['id' => 183, 'name' => 'Saint Vincent and the Grenadines', 'iso' => 'VC'],
        ['id' => 184, 'name' => 'Samoa', 'iso' => 'WS'],
        ['id' => 185, 'name' => 'San Marino', 'iso' => 'SM'],
        ['id' => 186, 'name' => 'Sao Tome and Principe', 'iso' => 'ST'],
        ['id' => 187, 'name' => 'Saudi Arabia', 'iso' => 'SA'],
        ['id' => 188, 'name' => 'Senegal', 'iso' => 'SN'],
        ['id' => 189, 'name' => 'Serbia and Montenegro', 'iso' => 'CS'],
        ['id' => 190, 'name' => 'Seychelles', 'iso' => 'SC'],
        ['id' => 191, 'name' => 'Sierra Leone', 'iso' => 'SL'],
        ['id' => 192, 'name' => 'Singapore', 'iso' => 'SG'],
        ['id' => 193, 'name' => 'Slovakia', 'iso' => 'SK'],
        ['id' => 194, 'name' => 'Slovenia', 'iso' => 'SI'],
        ['id' => 195, 'name' => 'Solomon Islands', 'iso' => 'SB'],
        ['id' => 196, 'name' => 'Somalia', 'iso' => 'SO'],
        ['id' => 197, 'name' => 'South Africa', 'iso' => 'ZA'],
        ['id' => 198, 'name' => 'South Georgia and the South Sandwich Islands', 'iso' => 'GS'],
        ['id' => 199, 'name' => 'Spain', 'iso' => 'ES'],
        ['id' => 200, 'name' => 'Sri Lanka', 'iso' => 'LK'],
        ['id' => 201, 'name' => 'Sudan', 'iso' => 'SD'],
        ['id' => 202, 'name' => 'Suriname', 'iso' => 'SR'],
        ['id' => 203, 'name' => 'Svalbard and Jan Mayen', 'iso' => 'SJ'],
        ['id' => 204, 'name' => 'Swaziland', 'iso' => 'SZ'],
        ['id' => 205, 'name' => 'Sweden', 'iso' => 'SE'],
        ['id' => 206, 'name' => 'Switzerland', 'iso' => 'CH'],
        ['id' => 207, 'name' => 'Syrian Arab Republic', 'iso' => 'SY'],
        ['id' => 208, 'name' => 'Taiwan, Province of China', 'iso' => 'TW'],
        ['id' => 209, 'name' => 'Tajikistan', 'iso' => 'TJ'],
        ['id' => 210, 'name' => 'Tanzania, United Republic of', 'iso' => 'TZ'],
        ['id' => 211, 'name' => 'Thailand', 'iso' => 'TH'],
        ['id' => 212, 'name' => 'Timor-Leste', 'iso' => 'TL'],
        ['id' => 213, 'name' => 'Togo', 'iso' => 'TG'],
        ['id' => 214, 'name' => 'Tokelau', 'iso' => 'TK'],
        ['id' => 215, 'name' => 'Tonga', 'iso' => 'TO'],
        ['id' => 216, 'name' => 'Trinidad and Tobago', 'iso' => 'TT'],
        ['id' => 217, 'name' => 'Tunisia', 'iso' => 'TN'],
        ['id' => 218, 'name' => 'Turkey', 'iso' => 'TR'],
        ['id' => 219, 'name' => 'Turkmenistan', 'iso' => 'TM'],
        ['id' => 220, 'name' => 'Turks and Caicos Islands', 'iso' => 'TC'],
        ['id' => 221, 'name' => 'Tuvalu', 'iso' => 'TV'],
        ['id' => 222, 'name' => 'Uganda', 'iso' => 'UG'],
        ['id' => 223, 'name' => 'Ukraine', 'iso' => 'UA'],
        ['id' => 224, 'name' => 'United Arab Emirates', 'iso' => 'AE'],
        ['id' => 225, 'name' => 'United Kingdom', 'iso' => 'GB'],
        ['id' => 226, 'name' => 'United States', 'iso' => 'US'],
        ['id' => 227, 'name' => 'United States Minor Outlying Islands', 'iso' => 'UM'],
        ['id' => 228, 'name' => 'Uruguay', 'iso' => 'UY'],
        ['id' => 229, 'name' => 'Uzbekistan', 'iso' => 'UZ'],
        ['id' => 230, 'name' => 'Vanuatu', 'iso' => 'VU'],
        ['id' => 231, 'name' => 'Venezuela', 'iso' => 'VE'],
        ['id' => 232, 'name' => 'Viet Nam', 'iso' => 'VN'],
        ['id' => 233, 'name' => 'Virgin Islands, British', 'iso' => 'VG'],
        ['id' => 234, 'name' => 'Virgin Islands, U.s.', 'iso' => 'VI'],
        ['id' => 235, 'name' => 'Wallis and Futuna', 'iso' => 'WF'],
        ['id' => 236, 'name' => 'Western Sahara', 'iso' => 'EH'],
        ['id' => 237, 'name' => 'Yemen', 'iso' => 'YE'],
        ['id' => 238, 'name' => 'Zambia', 'iso' => 'ZM'],
        ['id' => 239, 'name' => 'Zimbabwe', 'iso' => 'ZW'],
    ];

    protected function loadData(ObjectManager $manager): void
    {
        $this->createMany(count($this->countries), 'countries', function ($i) {
            $country = new Country();
            $country->setName($this->countries[$i]['name']);
            $country->setIso($this->countries[$i]['iso']);

            return $country;
        });

        $manager->flush();
    }
}
